[workspace]
authors = ["carlca <carl.caulkett@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly/"]
description = "Add a short description here"
name = "ca_mojo"
platforms = ["osx-arm64", "linux-64"]


[tasks]
t1 = { cmd = "mojo test_float_utils.mojo", env = { MODULAR_CRASH_REPORTING = "0" } }

tests = "pixi run t1"
default = "pixi run tests"
test = { cmd = "mojo test.mojo", env = { MODULAR_CRASH_REPORTING = "0" } }

[dependencies]
max = "*"
modular = ">=25.6.1.0,<28"
